apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-web-app
  labels:
    app: static-web-app
spec:
  replicas: 2  # Define the number of replicas as needed
  selector:
    matchLabels:
      app: static-web-app
  template:
    metadata:
      labels:
        app: static-web-app
    spec:
      containers:
      - name: static-web-app
        image: cloudops96/chandan-cloudops:static-web-app  # Custom image specified
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: static-web-app-service
spec:
  selector:
    app: static-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP  # Change to NodePort if needed
